server:
  port: 10086
spring:
  application:
    name: ly-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false #不注册到eureka
    fetch-registry: false  #不拉取服务
  server:
    eviction-interval-timer-in-ms: 10000